function f = dynamics(in1,u)
%DYNAMICS
%    F = DYNAMICS(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 08:48:55

theta = in1(2,:);
theta_dot = in1(3,:);
xdot = in1(1,:);
t2 = sin(theta);
t3 = t2.^2;
t4 = t3+1.0;
t5 = 1.0./t4;
t6 = cos(theta);
t7 = theta_dot.^2;
f = [xdot+(t5.*(u-t2.*(t6.*(9.81e2./1.0e2)-t7)))./2.0e1;theta+theta_dot./2.0e1;theta_dot-(t5.*(t2.*(-9.81e2./5.0e1)+t6.*u+t2.*t6.*t7))./2.0e1];
