function lf = final_cost(in1)
%FINAL_COST
%    LF = FINAL_COST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 08:48:55

theta = in1(2,:);
theta_dot = in1(3,:);
xdot = in1(1,:);
lf = theta.*(theta.*2.208509220963448e3+theta_dot.*5.99557137409261e2+xdot.*2.288702458483101e2)+xdot.*(theta.*2.288702458483101e2+theta_dot.*7.401019675759846e1+xdot.*5.428089944209434e1)+theta_dot.*(theta.*5.99557137409261e2+theta_dot.*1.683620803549041e2+xdot.*7.401019675759846e1);
