function [out1,out2,Qxx,Quu,Qux] = QInfo_DDP(in1,u,in3,in4)
%QINFO_DDP
%    [OUT1,OUT2,QXX,QUU,QUX] = QINFO_DDP(IN1,U,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 08:48:57

Vxx1_1 = in4(1);
Vxx1_2 = in4(4);
Vxx1_3 = in4(7);
Vxx2_1 = in4(2);
Vxx2_2 = in4(5);
Vxx2_3 = in4(8);
Vxx3_1 = in4(3);
Vxx3_2 = in4(6);
Vxx3_3 = in4(9);
lambda1 = in3(1,:);
lambda2 = in3(2,:);
lambda3 = in3(3,:);
theta = in1(2,:);
theta_dot = in1(3,:);
xdot = in1(1,:);
t2 = sin(theta);
t3 = cos(theta);
t4 = theta_dot.^2;
t5 = t2.^2;
t6 = t5+1.0;
t7 = 1.0./t6;
t8 = 1.0./t6.^2;
t9 = t3.*(9.81e2./1.0e2);
t10 = t3.*(9.81e2./5.0e1);
t11 = t3.^2;
t12 = t4.*t5;
t13 = t2.*u;
t28 = t4.*t11;
t14 = t10+t12+t13-t28;
t15 = (t7.*t14)./2.0e1;
t16 = t3.*u;
t17 = t2.*t3.*t4;
t29 = t2.*(9.81e2./5.0e1);
t18 = t16+t17-t29;
t19 = (t2.*t3.*t8.*t18)./1.0e1;
t20 = t15+t19;
t21 = t4-t9;
t22 = t3.*t21;
t23 = t5.*(9.81e2./1.0e2);
t24 = t22+t23;
t25 = (t7.*t24)./2.0e1;
t26 = (t2.*t3.*t7.*theta_dot)./1.0e1;
t27 = t26-1.0;
t30 = t2.*(t4-t9);
t31 = t30+u;
t33 = (t2.*t3.*t8.*t31)./1.0e1;
t32 = Vxx1_1.*(t25-t33);
t34 = t2.*t21;
out1 = [lambda1+xdot.*4.0;lambda2+theta.*(1.1e1./4.0)+lambda3.*t20+lambda1.*(t25-(t2.*t3.*t8.*(t34+u))./1.0e1);lambda2./2.0e1-lambda3.*t27+(lambda1.*t2.*t7.*theta_dot)./1.0e1];
if nargout > 1
    out2 = u.*(3.0./5.0)+(lambda1.*t7)./2.0e1-(lambda3.*t3.*t7)./2.0e1;
end
if nargout > 2
    t35 = 1.0./t6.^3;
    t36 = Vxx3_1.*t20;
    t37 = -t25+t33;
    t38 = Vxx3_3.*t20;
    t39 = Vxx2_1+t36-Vxx1_1.*t37;
    t40 = (Vxx1_1.*t2.*t7.*theta_dot)./1.0e1;
    t41 = Vxx2_2./2.0e1;
    t42 = Vxx2_1./2.0e1;
    t48 = Vxx3_1.*t27;
    t43 = t40+t42-t48;
    t44 = (t5.*t8.*t11.*theta_dot)./5.0;
    t45 = Vxx2_3./2.0e1;
    t46 = (Vxx1_3.*t2.*t7.*theta_dot)./1.0e1;
    t47 = t45+t46-Vxx3_3.*t27;
    Qxx = reshape([Vxx1_1+4.0,Vxx2_1+t32+t36,t43,Vxx1_2+t32+Vxx1_3.*t20,Vxx2_2+Vxx3_2.*t20-lambda3.*(t7.*(t16-t29+t2.*t3.*t4.*4.0).*(-1.0./2.0e1)+(t5.*t8.*t18)./1.0e1-(t8.*t11.*t18)./1.0e1+(t2.*t3.*t8.*t14)./5.0+t5.*t11.*t18.*t35.*(2.0./5.0))-t37.*t39+t20.*(Vxx2_3+t38+Vxx1_3.*(t25-t33))+Vxx1_2.*(t25-t33)-lambda1.*((t7.*(t34-t2.*t3.*2.943e1))./2.0e1-(t5.*t8.*t31)./1.0e1+(t8.*t11.*t31)./1.0e1+(t2.*t3.*t8.*t24)./5.0-t5.*t11.*t31.*t35.*(2.0./5.0))+1.1e1./4.0,t41+lambda3.*(t44+(t5.*t7.*theta_dot)./1.0e1-(t7.*t11.*theta_dot)./1.0e1)-Vxx3_2.*t27+t20.*t47-t37.*t43+(Vxx1_2.*t2.*t7.*theta_dot)./1.0e1+(lambda1.*t3.*t7.*theta_dot)./1.0e1-(lambda1.*t3.*t5.*t8.*theta_dot)./5.0,Vxx1_2./2.0e1+t40-Vxx1_3.*t27,t41+lambda1.*((t3.*t7.*theta_dot)./1.0e1-(t3.*t5.*t8.*theta_dot)./5.0)-t27.*(Vxx2_3+t38-Vxx1_3.*t37)-(Vxx1_2.*t37)./2.0e1+(Vxx3_2.*t20)./2.0e1+lambda3.*(t44+(t7.*(t5.*theta_dot.*2.0-t11.*theta_dot.*2.0))./2.0e1)+(t2.*t7.*t39.*theta_dot)./1.0e1,Vxx2_2./4.0e2-(Vxx3_2.*t27)./2.0e1-t27.*t47+(lambda1.*t2.*t7)./1.0e1+(Vxx1_2.*t2.*t7.*theta_dot)./2.0e2-(lambda3.*t2.*t3.*t7)./1.0e1+(t2.*t7.*t43.*theta_dot)./1.0e1],[3,3]);
end
if nargout > 3
    t49 = (Vxx1_1.*t7)./2.0e1;
    t53 = (Vxx3_1.*t3.*t7)./2.0e1;
    t50 = t49-t53;
    t51 = (Vxx1_3.*t7)./2.0e1;
    t54 = (Vxx3_3.*t3.*t7)./2.0e1;
    t52 = t51-t54;
    Quu = (t7.*t50)./2.0e1-(t3.*t7.*t52)./2.0e1+3.0./5.0;
end
if nargout > 4
    Qux = [t50,(Vxx1_2.*t7)./2.0e1+t20.*t52-t37.*t50-(Vxx3_2.*t3.*t7)./2.0e1+(lambda3.*t2.*t7)./2.0e1-(lambda1.*t2.*t3.*t8)./1.0e1+(lambda3.*t2.*t8.*t11)./1.0e1,(Vxx1_2.*t7)./4.0e2-t27.*t52-(Vxx3_2.*t3.*t7)./4.0e2+(t2.*t7.*t50.*theta_dot)./1.0e1];
end
